### PR TITLE
add plugin argument so Kakoune shows on dashboard chart

### PR DESCRIPTION
**Pull request by alanhamlett**
Untested, can you let me know if the Kakoune version and plugin version are correctly added to the command string?

### CODE REVIEW

**Comment by WhatNodyn** [comment]
Kakoune has no versioning scheme I'm aware of, and no standard way to get the current build number.
Maybe should I open an issue about this on their repo?

Also, the plugin name is set way earlier in code, during `wakatime-init`. If I understand right, the format is `<editor>/<version> <plugin>/<version>`?

**Comment by alanhamlett** [comment]
That format is correct, so for example a valid plugin string could look like:
`Kakoune/1.0.0 kakoune-wakatime/3.0.1`

For now, I'll update this PR to just remove the editor part since the editor can still be detected from  just `kakoune-wakatime/3.0.1`.

**Comment by alanhamlett** [comment]
Looks like the closest thing to a Kakoune version is the git hash:
https://github.com/mawww/kakoune/blob/0ecbc004a0c552533e0827474b5ba65c768f6335/contrib/make_deb.bash#L83

**Comment by WhatNodyn** [comment]
Indeed, I need to look more into it, see if it, or some kind of version number, can be made available to plugins.

I'll merge this and patch the few things that need to be.

**Comment by alanhamlett** [comment]
Thanks!

**Pull request merged**
